version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.6.1
    steps:
      - checkout
      - run:
          name: Run the test and linting
          command: |
            gem install bundler --no-document
            bundle install --jobs=4 --retry=3 --quiet
            bin/test
            bundle exec rubocop
