version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Run the test and linting
          command: |
            gem install bundler
            bundle install
            bin/test
            bundle exec rubocop
